#!/bin/sh

user=$USER@
OS="$(lsb_release -sirc)"
Desktop="${XDG_CURRENT_DESKTOP}"
Kernel="$(uname -sr)"
Uptime="$(uptime -p | sed 's/up //')"
Packages="$(dpkg -l | grep -c ^i)"
Shell="$(basename "$SHELL")"
CPU="$(lscpu | grep Model\ name | sed 's/name:\ //' | sed "s/([^)]*)/()/g" | sed 's/[)(]//g')" 
GPU="$(glxinfo -B | grep Device: | sed "s/([^)]*)/()/g" | sed 's/[)(]//g')"
RAM="$(free -h | awk '/^Mem:/ {print $3 "/" $2}')"
IP="$(hostname -I | awk '{print $1}')"
TERMINAL="$(update-alternatives --display x-terminal-emulator | grep  'link best version is /usr/bin/*' | sed 's/link best version is \/usr\/bin\///g')"

echo '                                         '
echo '                                         '
echo '              `..---+/---..`             '            $user$(hostname)
echo '          `---.``   ``   `.---.`         '            OS: $OS
echo '       .--.`        ``        `-:-.      '            Desktop: $Desktop			 
echo '     `:/:     `.----//----.`     :/-     '            Kernel: $Kernel
echo '    .:.    `---`          `--.`    .:`   '            Uptime: $Uptime
echo '   .:`   `--`                .:-    `:.  '            Packages: $Packages
echo '  `/    `:.      `.-::-.`      -:`   `/` '            Shell: $Shell
echo '  /.    /.     `:++++++++:`     .:    .: '            CPU: $CPU
echo ' `/    .:     `+++++++++++/      /`   `+`'            GPU: $GPU
echo ' /+`   --     .++++++++++++`     :.   .+:'            RAM: $RAM      
echo ' `/    .:     `+++++++++++/      /`   `+`'            IP:  $IP
echo '  /`    /.     `:++++++++:`     .:    .: '            TERMINAL: $TERMINAL
echo '  ./    `:.      `.:::-.`      -:`   `/` '
echo '   .:`   `--`                .:-    `:.  '
echo '    .:.    `---`          `--.`    .:`   '
echo '     `:/:     `.----//----.`     :/-     '
echo '       .-:.`        ``        `-:-.      '
echo '         `---.``   ``   `.---.`          '
echo '             `..---+/---..`              '
echo '                                         '
echo '                                         '
